
for i in `ls *.tsv`; do
  mv ${i} ${i%_mapped_reads_list.tsv}_mapped_reads_list_temp.tsv
  grep -v -e '@' ${i%_mapped_reads_list.tsv}_mapped_reads_list_temp.tsv > ${i}
done

for i in `ls *.tsv`; do
  python /safs-data02/dennislab/Public/scripts/fastq_filter_pairs_by_id.py -1 ../${i%_mapped_reads_list.tsv}_1.fq.gz -2 ../${i%_mapped_reads_list.tsv}_2.fq.gz -o ../mapped_reads_c__Nitrospiria/${i%cleaned_paired_mapped_reads_list.tsv}Nitrospiria -l ${i} --include
done


SD7448_S50_L004_cleaned_paired_mapped_reads_list.tsv

SD7448_S50_L004_cleaned_paired_2.fq.gz

for i in `ls Li_*`; do
  for j in `ls *fasta`; do
    echo ${j}
  done
    #mv ${i} /rdm/Q0775-uqbclar8/belle/01_core/01_5soils_AER/05_short_read_assembly/Li/01_bins
done
